development:
  adapter: postgresql
  database: demo_app_dev
  username: rth
  password: 

test:
  adapter: postgresql
  database: demo_app_test
  username: rth
  password: 

production:
  adapter: postgresql
  database: demo_app_live
  username: rth
  password: 
